import '../models/fire_event.dart';

class MockFireData {
  static const List<FireEvent> events = [
    FireEvent(
      id: '1',
      title: 'İzmir - Menderes',
      city: 'İzmir',
      district: 'Menderes',
      description: 'Orman yangını bildirildi. Ekipler aktif müdahale sürecinde.',
      status: 'Aktif',
      riskLevel: 'Yüksek',
      updatedAt: '14:20',
      startedAt: '12:45',
      affectedArea: '12.4 km²',
      windStatus: 'Kuvvetli',
      spreadRisk: 'Orta - Yüksek',
      lat: 38.249,
      lng: 27.138,
      recommendedActions: [
        'Bölgedeysen resmi yönlendirmeleri takip et ve açık alanlarda kalmaktan kaçın.',
        'Yakın çevredeysen acil çanta ve tahliye hazırlığını hazır tut.',
        'Yoğun duman durumunda kapalı alana geç ve mümkünse maske kullan.',
      ],
    ),
    FireEvent(
      id: '2',
      title: 'Muğla - Bodrum',
      city: 'Muğla',
      district: 'Bodrum',
      description: 'Ekipler müdahale ediyor. Bölge yakından izleniyor.',
      status: 'İzleniyor',
      riskLevel: 'Orta',
      updatedAt: '13:55',
      startedAt: '11:30',
      affectedArea: '6.8 km²',
      windStatus: 'Orta',
      spreadRisk: 'Orta',
      lat: 37.034,
      lng: 27.430,
      recommendedActions: [
        'Bölgede yaşayanlar resmi duyuruları düzenli olarak kontrol etsin.',
        'Gereksiz seyahat ve açık alanda uzun süre kalmaktan kaçınılsın.',
        'Tahliye uyarısı gelirse hızlı hareket etmek için temel hazırlık yap.',
      ],
    ),
    FireEvent(
      id: '3',
      title: 'Antalya - Kemer',
      city: 'Antalya',
      district: 'Kemer',
      description: 'Yangın kısmen kontrol altına alındı, ekip çalışması sürüyor.',
      status: 'Kontrol Altında',
      riskLevel: 'Düşük',
      updatedAt: '12:40',
      startedAt: '09:50',
      affectedArea: '3.1 km²',
      windStatus: 'Zayıf',
      spreadRisk: 'Düşük',
      lat: 36.602,
      lng: 30.559,
      recommendedActions: [
        'Yetkili ekiplerin belirlediği güvenlik şeridinin dışına çıkma.',
        'Bölgedeki duman yoğunluğu devam ediyorsa maske kullan.',
        'Yeni duyurular için uygulama bildirimlerini açık tut.',
      ],
    ),
  ];
}